# Site wide configuration

title: Discount Codes
logo:
search: true
url: http://127.0.0.1:4000
baseurl:

# Jekyll configuration

permalink:  /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
#  - jekyll-target-blank

target-blank:
    rel: nofollow

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

#include: []
exclude:
  - _original-theme-so-simple
  - Gemfile
  - Gemfile.lock
  - config
  - Capfile
  - README.md
  - _drafts/source_examples

# Site owner
owner:
  name: Discount Codes
  avatar:
  email: #email
  disqus-shortname: 
  twitter: 
  facebook:
  github:
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin:
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: G-ZJ1FYKHV7R
    verify:
    #ad-client: ca-pub-9952848327781387
    #ad-slot: 4958401589
  bing-verify:

t:
  en:
    description: The best for you
    flag: "&#x1F1EC;&#x1F1E7;"
    name: "English"
    page_locale: en_US
    html_locale: en
    translations:
      language: "language"
